api: /api/v1

spring:
  profiles:
    include: db

springdoc:
  title: Eco&Rich Test
  description: Eco&Rich coding test documentation
  version: 0.0.1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /**